"""
Django settings for myblog project.

Generated by 'django-admin startproject' using Django 2.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
from .base import *

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '_o34crhapyklz@hc29=e&g7p!u8qq#1-85%12btq9ahnt3el-('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases
'''
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}
'''
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'myblog_db',
        'USER': 'yyx',
        'PASSWORD': 'yyx123456',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}


# 发送邮件设置
# http://docs.djangoproject.com/en/2.0/ref/settings/#email
# http://docs.djangoproject.com/en/2.0/topics/email
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  # django默认配置
EMAIL_HOST = 'smtp.qq.com'
EMAIL_PORT = 25  # 端口号
EMAIL_HOST_USER = '997635832@qq.com'
EMAIL_HOST_PASSWORD = 'cekevsybbdypbchh'  # 授权码
EMAIL_SUBJECT_PREFIX = '[个人博客]'
EMAIL_USE_TLS = True  # 与SMTP服务器通信时，是否启动TLS链接（安全链接）


