# Generated by Django 2.2.7 on 2019-11-18 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20191119_0535'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
